import React, { ReactNode } from "react";
import Head from "next/head";

import Header from "./Header/Header";
import { Box } from "@mui/material";

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>spacex challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <Header />

      <Box component="div" p={2} mt={"70px"}>
        {children}
      </Box>
    </div>
  );
};

export default Layout;
